#!/bin/zsh
echo

# This script will run during an Xcode - Run Script Phase
echo Xcode: $XCODE_VERSION_ACTUAL
checkXcode() {
	required_xcode_version=700

	if [ ${XCODE_VERSION_ACTUAL} -lt ${required_xcode_version//.} ]
		then
		echo "\e[1;31m Error: Xcode ${required_xcode_version} or later is required to build ${PRODUCT_NAME} \e[0m"
		exit 1
	else
		echo "\e[1;32m	Good: 'Xcode' version is ${XCODE_VERSION_ACTUAL} \e[0m"

		# Check if we have all frameworks
		checkFrameworks
	fi
}

checkFrameworks() {
	read -d '' items < <(ls ${PROJECT_DIR}/Carthage/build/Mac |grep framework$)
	if [ ${#items[*]} -ge 6 ]
		then
		echo "\e[1;32m	Good: all frameworks are present \e[0m"
	else
		echo "\e[1;31m	Bad: Frameworks missing, bootstrapping \e[0m"
		checkCarthage
		`carthage bootstrap ${PROJECT_DIR} --platform mac`
	fi
}

checkBrew() {
	local brew=`where brew`

	if [ -x $brew ]
		then
		echo "\e[1;32m	Good: 'brew' is installed in $brew \e[0m"
	else
		echo "\e[1;31m	Bad: 'brew' is not installed... \e[0m"
		echo
		echo "\e[1;36m	May I install 'brew' for you? \e[0m"

		read response
		if [ $response = "yes" ] || [ $response = "y" ]
			then

			ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
			sleep 1
			checkBrew
		else
			echo "\e[1;31m	Unfortunately Setup can not continue... \e[0m"

			exit 1
		fi
	fi
}

checkCarthage() {
	local carthage=`where carthage`
	if [ $? -eq 0 ]
		then
		echo "\e[1;32m	Good: 'Carthage' is installed in $carthage \e[0m"
	else
		checkBrew
		echo "\e[1;36m	updating 'brew'... \e[0m"
		brew update >>/dev/null
		echo "\e[1;36m	Fix: installing 'Carthage' \e[0m"
		brew install carthage
		sleep 1
		checkCarthage
	fi
}

checkSwiftLint() {
	local swiftlint=`where swiftlint`
	if [ $? -eq 0 ]
		then
		echo "\e[1;32m	Good: 'SwiftLint' is installed in $swiftlint \e[0m"
	else
		checkBrew
		echo "\e[1;36m	updating 'brew'... \e[0m"
		brew update >>/dev/null
		echo "\e[1;36m	Fix: installing 'SwiftLint' \e[0m"
		brew install swiftlint
		sleep 1
		checkSwiftLint
	fi
}

checkXcode
checkSwiftLint
