#!/bin/sh
TAGS="TODO:|FIXME:|CHRIS:|LEO:"
find "${SRCROOT}/Cast" \( -name "*.h" -or -name "*.m" -or -name "*.swift" \) -print0 | xargs -0 egrep --with-filename --line-number --only-matching "($TAGS).*\$" | perl -p -e "s/($TAGS)/ warning: \$1/"
exit 0
